DOANWEB/DOANWEB/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DOANWEB.Models;

namespace DOANWEB.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: TrangChu
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult head()
        {
            return View();
        }

    }
}

DOANWEB/DOANWEB/Views/Admin/Create.cshtml
@model DOANWEB.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.maloaisp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maloaisp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maloaisp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tensp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tensp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tensp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giaban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giaban, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giaban, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngaycapnhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaycapnhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaycapnhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soluongton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluongton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soluongton, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Listsp","Admin")
</div>

DOANWEB/DOANWEB/Views/Admin/DangNhap.cshtml
@model DOANWEB.Models.Admin

@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DangNhap</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Admin</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TenDangNhapAdmin, "Tên đăng nhập:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenDangNhapAdmin, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenDangNhapAdmin, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MatKhauAdmin, "Mật khẩu:", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MatKhauAdmin, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MatKhauAdmin, "", new { @class = "text-danger" })
        </div>
    </div>

    }

    <div>
        @Html.ActionLink("Back to List", "Index","TrangChu")
    </div>

DOANWEB/DOANWEB/Views/Admin/Delete.cshtml
@model DOANWEB.Models.SanPham

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.maloaisp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maloaisp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tensp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tensp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giaban)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.giaban)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaycapnhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaycapnhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soluongton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluongton)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Listsp")
        </div>
    }
</div>

DOANWEB/DOANWEB/Views/Admin/Detail.cshtml
@model DOANWEB.Models.SanPham

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.maloaisp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.maloaisp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tensp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tensp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.hinh)
        </dt>

        <dd>
            <img src="@Model.hinh" alt="hinh thumbnail" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.giaban)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.giaban)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaycapnhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaycapnhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soluongton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soluongton)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.masp }) |
    @Html.ActionLink("Back to List", "Listsp")
</p>

DOANWEB/DOANWEB/Views/Admin/Edit.cshtml
@model DOANWEB.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>SanPham</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.masp)

        <div class="form-group">
            @Html.LabelFor(model => model.maloaisp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.maloaisp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.maloaisp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.tensp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.tensp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.tensp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.hinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.hinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.giaban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.giaban, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.giaban, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ngaycapnhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ngaycapnhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ngaycapnhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soluongton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soluongton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soluongton, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div class="form-group">
    <div class="col-md-10">
        <strong>Hình</strong>
        @Html.EditorFor(model => model.hinh, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.hinh, "", new { @class = "text-danger" })
        <input type="file" name="fileUpload" id="fileUpload" accept="image/*"
               style="display:none;" />
        <input type="button" id="btnUpload" value="Chọn" class="btn btn-success" />
        <img src="@Model.hinh" id="pictureUpload" />
    </div>
</div>
@section upload
{
    <script>
        $(function () {
            $('#btnUpload').click(function () {
                $('#fileUpload').trigger('click');
            });
        });
        $('#fileUpload').change(function () {
            if (window.FormData !== undefined) {
                var fileUpload = $('#fileUpload').get(0);
                var files = fileUpload.files;
                var formData = new FormData();
                formData.append('file', files[0]);

                $.ajax(
                    {
                        type: 'POST',
                        url: '/Admin/ProcessUpload',
                        contentType: false,
                        processData: false,
                        data: formData,
                        success: function (urlImage) {

                            $('#pictureUpload').attr('src', urlImage);
                            $('#hinh').val(urlImage);
                        },
                        error: function (err) {
                            alert('Error ', err.statusText);
                        }
                    });
            }
        });
    </script>
}

<div>
    @Html.ActionLink("Back to List", "Listsp")
</div>

DOANWEB/DOANWEB/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/TrangChu/head.cshtml";
}


<div class="header">

    <div class="navbar">
        <div class="navbar__left">



            <div style="justify-content: space-between;" class="navbar__menu">
                <i id="bars" class="fa fa-bars" aria-hidden="true"></i>
                <ul>
                    <li>@Html.ActionLink("Quản Lý Sản Phẩm", "Listsp", "Admin")</li>
                    <li>@Html.ActionLink("Quản Lý Đơn Hàng", "ListDonHang", "Admin")</li>
                    <li>@Html.ActionLink("Quản Lý Chi tiết đơn hàng", "Listchitiet", "Admin")</li>


                </ul>



            </div>

        </div>

</div>

DOANWEB/DOANWEB/Views/Admin/ListDonHang.cshtml
@model IEnumerable<DOANWEB.Models.DONHANG>
@{
    ViewBag.Title = "ListDonHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản Lý Đơn Hàng</h2>

<table class="table">
    <tr>
        <th> Mã Đơn </th>
        <th> Thanh Toán</th>
        <th> Giao Hàng </th>
        <th> Ngày Đặt</th>
        <th> Ngày Giao </th>
        <th> Mã Khách Hàng</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.MaDon)</td>
            <td>@Html.DisplayFor(modelItem => item.ThanhToan)</td>

            <td>@Html.DisplayFor(modelItem => item.GiaoHang)</td>
            <td>@Html.DisplayFor(modelItem => item.NgayDat)</td>
            <td>@Html.DisplayFor(modelItem => item.NgayGiao)</td>
            <td>@Html.DisplayFor(modelItem => item.MaKH)</td>

        </tr>
    }
</table>

<div>
    @Html.ActionLink("Back to List", "Index", "Admin")
</div>

DOANWEB/DOANWEB/Views/Admin/Listchitiet.cshtml
@model IEnumerable<DOANWEB.Models.CHITIETDONHANG>
@{
    ViewBag.Title = "Listchitiet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản Lý Đơn Hàng</h2>

<table class="table">
    <tr>
        <th> Mã Đơn </th>
        <th> Mã Sản Phẩm</th>
        <th> Số Lượng </th>
        <th> Giá</th>
      
    @foreach (var item in Model)
    {
    <tr>
        <td>@Html.DisplayFor(modelItem => item.MaDon)</td>
        <td>@Html.DisplayFor(modelItem => item.masp)</td>
        <td>@Html.DisplayFor(modelItem => item.SoLuong)</td>
        <td>@Html.DisplayFor(modelItem => item.Gia)</td>

    </tr>
    }
</table>

<div>
    @Html.ActionLink("Back to List", "Index","Admin")
</div>

DOANWEB/DOANWEB/Views/Admin/Listsp.cshtml
@model IEnumerable<DOANWEB.Models.SanPham>
@{
    ViewBag.Title = "Listsp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Quản Lý Sản Phẩm</h2>>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th> Mã loại </th>
        <th> Tên sách</th>
        <th> Hình </th>
        <th> Giá bán</th>
        <th> Ngày cập nhật </th>
        <th> Số lượng tồn</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.maloaisp)</td>
            <td>@Html.DisplayFor(modelItem => item.tensp)</td>
            <td><img src="@item.hinh" alt="hinh thumbnail" /></td>
            <td>@Html.DisplayFor(modelItem => item.giaban)</td>
            <td>@Html.DisplayFor(modelItem => item.ngaycapnhat)</td>
            <td>@Html.DisplayFor(modelItem => item.soluongton)</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.masp}) |
                @Html.ActionLink("Detail", "Detail", new { id = item.masp }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.masp })
            </td>
        </tr>
    }
</table>

<div>
    @Html.ActionLink("Back to List", "Index", "Admin")
</div>